name: Release Latest Artifact

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: build-artifact
          path: dist

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          release_name: Latest Successful Release
          body: "This is the latest successful build."
          draft: false
          prerelease: false
          files: dist/*
